AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - spec/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact